platform :ios, '8.0'

xcodeproj 'sHome.xcodeproj'

target "sHome" do

#pod 'HekrSDK' :path => './HEKR-IOS-SDK-global'
pod 'HekrSDK', :podspec => 'https://raw.githubusercontent.com/HEKR-Cloud/HEKR-IOS-SDK/global/HekrSDK.podspec'

pod 'ReactiveCocoa', '~> 2.5'
pod 'SDWebImage', '~> 3.7.5'
pod 'JSONModel', '~> 1.0.1'
pod 'FMDB/common' , '~>2.5'
pod 'FMDB/SQLCipher', '~>2.5'
pod 'ActionSheetPicker-3.0'
pod 'XAspect'
pod 'IQKeyboardManager'
pod 'LBXScan','~> 1.1.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'MWPhotoBrowser'
pod 'LBXScan','~> 1.1.1'
#pod 'LKDBHelper'
pod 'M13ProgressSuite', '~> 1.2.7'
pod 'pop'
pod 'YYText'
pod 'LCActionSheet'
pod 'CocoaAsyncSocket'
pod 'SAMKeychain'
pod 'Fabric'
pod 'Crashlytics'
pod 'Firebase'
pod 'FirebaseCore'
pod 'FirebaseMessaging'

end
